/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[6],{166:function(Ba,ua,r){function pa(Sa,Ka,xa,Ja){return Object(ca.b)(void 0,void 0,void 0,function(){var Ha,Qa,Ua,Ra,Ea,Ga,Va,Wa,Za;return Object(ca.d)(this,function(eb){switch(eb.label){case 0:return Ha=La.getDocument(),Qa=[1],[4,Object(ia.c)(Ka,{extension:"pdf"})];case 1:return Ua=eb.ea(),Ra=La.qa(),Va=(Ga=oa.a).Dga,[4,Ua.VB()];case 2:return Ea=Va.apply(Ga,[eb.ea().xfdfString,Sa]),Wa=!0,[4,Ha.Bf(Ua,Qa,Sa,Wa)];case 3:return eb.ea(),
[4,Ha.mg([Sa+1],Wa)];case 4:return eb.ea(),Za=Ra.qb().filter(function(fb){return fb.fK()&&fb.PageNumber===Sa}),Ra.Ah(Za,{force:!0,source:"contentEditTool"}),[4,Ra.OJ(Ea)];case 5:return eb.ea(),La.getDocument().zL(),La.yL(Sa),La.Ve(),ha(Sa),f(Sa,xa.galleys,Ja),f(Sa,xa.objects,Ja),[2]}})})}function ka(Sa){Sa=(new DOMParser).parseFromString(Sa,"text/html").documentElement.querySelector("body");Sa.querySelectorAll("p").forEach(function(Ka){Ka.querySelectorAll("span").forEach(function(Ha){var Qa=Ha.getAttribute("style");
Qa=ma(Qa,Ha.innerHTML);Ha.innerHTML=Qa});var xa=Ka.getAttribute("style"),Ja=Ka.innerHTML.replaceAll("<br>","");Ka.innerHTML=ma(xa,Ja)});return Sa.innerHTML.trim()}function ma(Sa,Ka){Sa.includes("bold")&&(Ka="<strong>"+Ka+"</strong>");Sa.includes("italic")&&(Ka="<em>"+Ka+"</em>");Sa.includes("text-decoration: underline")&&(Ka="<u>"+Ka+"</u>");return Ka}function ha(Sa){var Ka=La.qa(),xa=Ka.qb().filter(function(Ja){return Ja.Mh()&&Ja.PageNumber===Sa});Ka.Ah(xa,{force:!0,source:"contentEditTool"})}function da(Sa,
Ka){Ka.forEach(function(xa){Ma[Sa]||(Ma[Sa]=[]);Ma[Sa].find(function(Ja){return Ja.id===xa.id})||Ma[Sa].push(xa)})}function aa(Sa,Ka){Ka.forEach(function(xa){Ia[Sa]||(Ia[Sa]=[]);Ia[Sa].find(function(Ja){return Ja.id===xa.id})||Ia[Sa].push(xa)})}function x(Sa){var Ka=new DOMParser,xa=Ka.parseFromString(Sa,"text/xml");xa.querySelector("parsererror")&&(xa=Ka.parseFromString("<Root>"+Sa+"</Root>","text/xml"));xa.querySelectorAll("a").forEach(function(Ja){var Ha=Ja.childNodes[0];Array.from(Ja.querySelectorAll("*")).find(function(Qa){return"u"===
Qa.tagName.toLowerCase()})||(Ja=document.createElement("u"),Ha.after(Ja),Ja.appendChild(Ha))});return(new XMLSerializer).serializeToString(xa)}function y(Sa,Ka,xa,Ja){this.top=Sa;this.left=Ka;this.bottom=xa;this.right=Ja;this.topVal=function(){return Math.round(this.top)};this.bottomVal=function(){return Math.round(this.bottom)};this.leftVal=function(){return Math.round(this.left)};this.rightVal=function(){return Math.round(this.right)};this.height=function(){return Math.round(Math.abs(this.top-this.bottom))};
this.width=function(){return Math.round(this.right-this.left)};this.UQ=function(Ha){return this.topVal()!==Ha.topVal()||this.leftVal()!==Ha.leftVal()||this.bottomVal()!==Ha.bottomVal()||this.rightVal()!==Ha.rightVal()}}function h(Sa,Ka,xa,Ja,Ha){this.id=Sa;this.pagenum=Ka;this.galleysContents=xa;this.contents=Ja;this.galleyBox=Ha;Object(va.k)(Ia)}function e(Sa,Ka,xa,Ja){this.id=Ka;this.type=Sa;this.bbox=xa;this.pagenum=Ja}function b(Sa,Ka,xa,Ja,Ha){this.id=Sa;this.pagecount=Ka;this.pageBBox=xa;this.galleys=
Ja;this.objects=Ha}function a(Sa,Ka,xa,Ja,Ha){var Qa=[];(new DOMParser).parseFromString(Ja,"text/html").documentElement.querySelectorAll("p").forEach(function(Ga,Va){Qa[Va]=Ga.innerHTML});xa=(new DOMParser).parseFromString(xa,"text/html");var Ua=null;xa.documentElement.querySelectorAll("p").forEach(function(Ga,Va){Va<Qa.length?(Ga.innerHTML=Qa[Va],Ua=Ga.getAttribute("style"),Ua=Ua.replace("font:italic","font:normal"),Ua=Ua.replace(" bold "," normal "),Ua=Ua.replace("underline:1;","underline:0;"),
Ga.setAttribute("style",Ua)):Ga.remove()});for(Ja=xa.documentElement.querySelectorAll("p").length;Ja<Qa.length;Ja++){var Ra=document.createElement("p");Ra.setAttribute("id","0");Ra.innerHTML=Qa[Ja];null!=Ua&&Ra.setAttribute("style",Ua);xa.documentElement.querySelector("body").appendChild(Ra)}xa=xa.documentElement.querySelector("body").innerHTML;var Ea="";Ia[Sa].forEach(function(Ga){Ga.id===Ha&&(Ea=Ga)});if(""===Ea)return"";Ka="<DOC id='"+Ka.id+"' pagecount='"+Ka.pagecount+"'>";Ka=Ka+("<STORY galley_ids='"+
Ha+"' pagenum='"+Sa+"'><galleys>")+(Ea.galleysContents+"</galleys>");Ea.contents=xa;Ka=Ka+xa+"\n</STORY>";return Ka+="</DOC>"}function f(Sa,Ka,xa){var Ja=[],Ha=La.getDocument(),Qa=null;Ka.forEach(function(Ua){if(Ua instanceof e){var Ra=Ha.Mn(Sa,Ua.bbox.leftVal(),Ua.bbox.topVal());var Ea=Ra.x;var Ga=Ra.y;var Va=Ha.Mn(Sa,Ua.bbox.rightVal(),Ua.bbox.bottomVal());Ra=Va.x;Va=Va.y}else if(Ua instanceof h)Ra=Ha.Mn(Sa,Ua.galleyBox.leftVal(),Ua.galleyBox.topVal()),Ea=Ra.x,Ga=Ra.y,Va=Ha.Mn(Sa,Ua.galleyBox.rightVal(),
Ua.galleyBox.bottomVal()),Ra=Va.x,Va=Va.y;else return;var Wa=new window.Core.Annotations.RectangleAnnotation,Za=ta.a.OBJECT;Ua instanceof h&&(Za=ta.a.TEXT);Wa.hja(Ua,Za);Wa.PageNumber=Ua.pagenum;Wa.X=Ea;Wa.Y=Ga;Wa.Width=Ra-Ea;Wa.Height=Va-Ga;Wa.StrokeColor=new fa.a("#3183C8");Wa.FillColor=new fa.a(255,255,255,.01);Wa.Style="dash";Wa.Dashes="4,3";Wa.FB();Wa.selectionModel=la.a;Ja.push(Wa);"undefined"!==typeof xa&&xa===Ua.id&&(Qa=Wa)});Ka=La.qa();Ka.Gg(Ja);Qa&&Ka.ih(Qa);Ka.de(Ja)}function n(Sa,Ka,xa){return Object(ca.b)(this,
void 0,void 0,function(){var Ja,Ha,Qa,Ua,Ra;return Object(ca.d)(this,function(Ea){switch(Ea.label){case 0:Ja=Sa.data;Qa=Ja.cmd;switch(Qa){case "isReady":return[3,1];case "initialiseInfixServer":return[3,3];case "exportFile":return[3,4];case "importText":return[3,5];case "transformObject":return[3,5];case "deleteObject":return[3,6]}return[3,7];case 1:return[4,Object(qa.b)()];case 2:return Ua=Ea.ea(),wa.postMessage({cmd:"initialiseInfixServer",l:Ua}),[3,7];case 3:return(Ra=z(Ja.resultsXML))?Ka():xa("License key does not have content edit permission"),
[3,7];case 4:return Ja.exportPerformed?w(Ja.pageNumber,Ja.exportXML,Ja.objectXML,Ja.resultsXML):(Ha=Ca[Ja.pageNumber],aa(Ja.pageNumber,Ha.galleys),da(Ja.pageNumber,Ha.objects),ha(Ja.pageNumber),f(Ja.pageNumber,Ha.galleys),f(Ja.pageNumber,Ha.objects)),[3,7];case 5:return Ha=Ca[Ja.pageNumber],ba(Ja.pageNumber,Ja.resultsXML),pa(Ja.pageNumber,Ja.pdfBuffer,Ha,Ja.id),[3,7];case 6:return Ha=Ca[Ja.pageNumber],ba(Ja.pageNumber,Ja.resultsXML),Ha.galleys=Ha.galleys.filter(function(Ga){return Ga.id!==Ja.id}),
Ha.objects=Ha.objects.filter(function(Ga){return Ga.id!==Ja.id}),pa(Ja.pageNumber,Ja.pdfBuffer,Ha),[3,7];case 7:return[2]}})})}function z(Sa){Sa=new Uint8Array(Sa);var Ka=(new TextDecoder("utf-8")).decode(Sa);Sa=!1;Ka=(new DOMParser).parseFromString(Ka,"text/xml").getElementsByTagName("LicenseCheck");null!==Ka&&0<Ka.length&&(Ka=Ka[0].getElementsByTagName("Status")[0].innerHTML,"error"!==Ka&&"ok"===Ka&&(Sa=!0));return Sa}function w(Sa,Ka,xa,Ja){var Ha=new Uint8Array(Ka),Qa=new TextDecoder("utf-8");
Ka=Qa.decode(Ha);Ha=new Uint8Array(xa);xa=Qa.decode(Ha);Ha=new Uint8Array(Ja);Ja=Qa.decode(Ha);Ca[Sa]=ja(Sa,Ka,xa,Ja);Ja=Ca[Sa];aa(Sa,Ja.galleys);da(Sa,Ja.objects);ha(Sa);f(Sa,Ja.galleys);f(Sa,Ja.objects)}function ea(Sa,Ka){Sa=parseFloat(Sa);return isNaN(Ka)||Ka<Sa?Sa:Ka}function ja(Sa,Ka,xa,Ja){var Ha;var Qa=new DOMParser;Ja=Qa.parseFromString(Ja,"text/xml");Array.prototype.slice.call(Ja.getElementsByTagName("BBox")).forEach(function(Ea){if("CropBox"===Ea.getAttribute("Name")){var Ga=parseFloat(Ea.getElementsByTagName("Top").item(0).innerHTML),
Va=parseFloat(Ea.getElementsByTagName("Bottom").item(0).innerHTML),Wa=parseFloat(Ea.getElementsByTagName("Left").item(0).innerHTML);Ea=parseFloat(Ea.getElementsByTagName("Right").item(0).innerHTML);Ha=new y(Ga,Wa,Va,Ea)}});Qa=new DOMParser;Ja=Qa.parseFromString(Ka,"text/xml");var Ua=[];Array.prototype.slice.call(Ja.getElementsByTagName("STORY")).forEach(function(Ea){var Ga=Ea.getAttribute("galley_ids"),Va=Array.prototype.slice.call(Ea.getElementsByTagName("g"))[0],Wa=Va.getAttribute("bbox").split(" ");
Wa=new y(parseFloat(Wa[0]),parseFloat(Wa[1]),parseFloat(Wa[2]),parseFloat(Wa[3]));Va=Va.innerHTML;var Za=Array.prototype.slice.call(Ea.getElementsByTagName("galleys"))[0];Za.parentNode.removeChild(Za);Ea=Ea.innerHTML;Ea=(new DOMParser).parseFromString(Ea,"text/html").documentElement.querySelector("body").innerHTML.trim();Ga=new h(Ga,Sa,Va,Ea,Wa);Ua.push(Ga)});Qa=new DOMParser;var Ra=[];Ka=Qa.parseFromString(xa,"text/xml").getElementsByTagName("Object");Array.prototype.slice.call(Ka).forEach(function(Ea){var Ga=
Ea.getAttribute("Type"),Va=Ea.getAttribute("OID");Ea=Array.prototype.slice.call(Ea.getElementsByTagName("Point"));var Wa=Number.NaN,Za=Number.NaN,eb=Number.NaN,fb=Number.NaN;Ea.forEach(function(hb){var mb=hb.getAttribute("Name");"TL"===mb?(Wa=ea(hb.getAttribute("Y"),Wa),eb=ea(hb.getAttribute("X"),eb)):"TR"===mb?(Wa=ea(hb.getAttribute("Y"),Wa),fb=ea(hb.getAttribute("X"),fb)):"BR"===mb?(Za=ea(hb.getAttribute("Y"),Za),fb=ea(hb.getAttribute("X"),fb)):"BL"===mb&&(Za=ea(hb.getAttribute("Y"),Za),eb=ea(hb.getAttribute("X"),
eb))});Ea=new y(Wa,eb,Za,fb);Ga=new e(Ga,Va,Ea,Sa);Ra.push(Ga)});Ka=Array.prototype.slice.call(Ja.getElementsByTagName("DOC"))[0].getAttribute("id");return new b(Ka,1,Ha,Ua,Ra)}function ba(Sa,Ka){var xa;Ka=(new TextDecoder("utf-8")).decode(Ka);var Ja=(new DOMParser).parseFromString(Ka,"text/xml");Ka=Ja.getElementsByTagName("Galley").item(0);if(null!=Ka){var Ha=Ka.getAttribute("id");Ka=Ja.getElementsByTagName("BBox");Ka=Array.prototype.slice.call(Ka);Ka.forEach(function(Ra){var Ea=Ra.getElementsByTagName("Top"),
Ga=parseFloat(Ea.item(0).innerHTML);Ea=Ra.getElementsByTagName("Left");var Va=parseFloat(Ea.item(0).innerHTML);Ea=Ra.getElementsByTagName("Bottom");var Wa=parseFloat(Ea.item(0).innerHTML);Ea=Ra.getElementsByTagName("Right");Ra=parseFloat(Ea.item(0).innerHTML);xa=new y(Ga,Va,Wa,Ra)});Ia[Sa].forEach(function(Ra){Ra.id===Ha&&!0===xa.UQ(Ra.galleyBox)&&(Ra.galleyBox=xa)})}Ka=Ja.getElementsByTagName("Object").item(0);if(null!=Ka){var Qa=Ka.getAttribute("OID");Ka=Ja.getElementsByTagName("BBox");Ka=Array.prototype.slice.call(Ka);
Ka.forEach(function(Ra){var Ea=Ra.getElementsByTagName("Top"),Ga=parseFloat(Ea.item(0).innerHTML);Ea=Ra.getElementsByTagName("Left");var Va=parseFloat(Ea.item(0).innerHTML);Ea=Ra.getElementsByTagName("Bottom");var Wa=parseFloat(Ea.item(0).innerHTML);Ea=Ra.getElementsByTagName("Right");Ra=parseFloat(Ea.item(0).innerHTML);xa=new y(Ga,Va,Wa,Ra)});Ma[Sa].forEach(function(Ra){Ra.id===Qa&&!0===xa.UQ(Ra.bbox)&&(Ra.bbox=xa)})}Ka=Ja.getElementsByTagName("NewParas").item(0);if(null!=Ka){var Ua=Ka.getAttribute("id");
Ia[Sa].forEach(function(Ra){if(Ra.id===Ua){var Ea="<Contents>"+Ra.contents;Ea+="</Contents>";var Ga=Array.prototype.slice.call(Ja.getElementsByTagName("NewPara"));Ea=(new DOMParser).parseFromString(Ea,"text/xml");var Va=Array.prototype.slice.call(Ea.getElementsByTagName("p"));Ga.forEach(function(Wa){var Za=parseFloat(Wa.innerHTML),eb=!1;Va.forEach(function(fb){var hb=fb.getAttribute("id");!1===eb&&"0"===hb&&(fb.setAttribute("id",Za),eb=!0)})});Ra.contents=Ea.getElementsByTagName("Contents").item(0).innerHTML}})}}
r.r(ua);var ca=r(1),ia=r(55),fa=r(7),la=r(470),na=r(37),qa=r(76),ra=r(2),ta=r(175),va=r(94),oa=r(6),wa=null,Da=null,Ia={},Ma={},Ca={},La;ua["default"]={zga:function(Sa){return Object(ca.b)(void 0,void 0,void 0,function(){return Object(ca.d)(this,function(){Da||(La=Sa,Da=new Promise(function(Ka,xa){var Ja=window.Core.ContentEdit.getWorkerPath(),Ha=window.Core.ContentEdit.getResourcePath();wa=new Worker(Ja+"InfixServerModule.js?resourcePath="+Ha);wa.onmessage=function(Qa){n(Qa,Ka,xa)};wa.postMessage({cmd:"isReady"})}));
return[2,Da]})})},Bga:function(Sa,Ka,xa){return Object(ca.b)(void 0,void 0,void 0,function(){var Ja,Ha,Qa,Ua;return Object(ca.d)(this,function(Ra){switch(Ra.label){case 0:return ha(Ka),Ia[Ka]=[],Ma[Ka]=[],[4,Sa.Ge([Ka])];case 1:return Ja=Ra.ea(),Ha=new TextEncoder,Qa=Ha.encode(""),Ua=Qa.buffer,wa.postMessage({cmd:"exportFile",pageNumber:Ka,performExport:xa,pdfFile:Ja,tableData:Ua},[Ja,Ua]),[2]}})})},r7:function(Sa){return Object(ca.b)(void 0,void 0,void 0,function(){var Ka,xa,Ja,Ha,Qa,Ua,Ra,Ea;return Object(ca.d)(this,
function(Ga){switch(Ga.label){case 0:return Ka=Sa.id,xa=Sa.isText,Ja=Sa.pageNumber,Ha=La.getDocument(),[4,Ha.Ge([Ja])];case 1:return Qa=Ga.ea(),Ua=new TextEncoder,Ra=Ua.encode(""),Ea=Ra.buffer,wa.postMessage({cmd:"deleteObject",pdfFile:Qa,pageNumber:Ja,objectID:Ka,isText:xa,tableData:Ea},[Ea]),[2]}})})},Qla:function(Sa){return Object(ca.b)(void 0,void 0,void 0,function(){var Ka,xa,Ja,Ha,Qa,Ua,Ra,Ea,Ga,Va,Wa,Za,eb;return Object(ca.d)(this,function(fb){switch(fb.label){case 0:return Ka=Sa.id,xa=Sa.position,
Ja=xa.top,Ha=xa.left,Qa=xa.bottom,Ua=xa.right,Ra=Sa.isText,Ea=Sa.pageNumber,Ga=La.getDocument(),[4,Ga.Ge([Ea])];case 1:return Va=fb.ea(),Wa=new TextEncoder,Za=Wa.encode(""),eb=Za.buffer,wa.postMessage({cmd:"transformObject",pdfFile:Va,pageNumber:Ea,objectID:Ka,isText:Ra,topVal:Ja,leftVal:Ha,bottomVal:Qa,rightVal:Ua,tableData:eb},[eb]),[2]}})})},hma:function(Sa,Ka){return Object(ca.b)(void 0,void 0,void 0,function(){var xa,Ja,Ha,Qa,Ua,Ra,Ea,Ga,Va,Wa,Za,eb,fb,hb,mb,yb,qb,vb;return Object(ca.d)(this,
function(Eb){switch(Eb.label){case 0:xa=Ka.replaceAll("<p><br></p>","");Ja=x(xa);Ja=Ja.replace(/<span style="color: var\(--text-color\);">(.*?)<\/span>/g,"$1");Ha=Sa.Iu.id;Qa=Sa.PageNumber;Ua=Ca[Qa];Ra=Ua.galleys.find(function(Fb){return Fb.id===Ha});Ea=ka(Ra.contents);Ga=a(Qa,Ua,Ea,Ja,Ha);if(""===Ga)return[3,2];Va=new TextEncoder;Wa=Va.encode(Ga);Za=Wa.buffer;eb=Object(na.c)()||"https://www.pdftron.com/webfonts/v2/";fb=La.getDocument();return[4,fb.Ge([Qa])];case 1:return hb=Eb.ea(),Va=new TextEncoder,
mb=Va.encode(""),yb=mb.buffer,wa.postMessage({cmd:"importText",pdfFile:hb,pageNumber:Qa,webFontURL:eb,galleyId:Ha,importData:Za,tableData:yb},[Za,yb]),qb={},Ra&&(vb=Ra.galleyBox,qb={top:vb.top,left:vb.left,bottom:vb.bottom,right:vb.right}),Object(va.l)(Ea,Ja,qb),[3,3];case 2:Object(ra.g)("Unable to generate import XML"),Eb.label=3;case 3:return[2]}})})},Faa:function(Sa){if(Sa)return ka(Sa.contents);Object(ra.g)("Unable to extract document content")}}},470:function(Ba,ua,r){var pa=r(1);Ba=r(83);var ka=
r(48);r=function(ma){function ha(){return null!==ma&&ma.apply(this,arguments)||this}Object(pa.c)(ha,ma);ha.prototype.testSelection=function(da,aa,x){return ka.a.al(da,aa,x)};return ha}(Ba.a);ua.a=r}}]);}).call(this || window)
