/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{444:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(471),ma=r(472),ha;(function(da){da[da.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";da[da.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";da[da.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ha||(ha={}));Ba=function(){function da(aa){this.aa=aa;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED}da.prototype.wca=function(){var aa=this;return function(x,
y,h){return Object(pa.b)(aa,void 0,void 0,function(){var e,b,a,f,n,z,w,ea=this,ja;return Object(pa.d)(this,function(ba){switch(ba.label){case 0:if(this.state!==ha.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().vs();return[4,this.Kaa(e)];case 1:b=ba.ea(),a=this.J6(b),this.oI=null!==(ja=null===a||void 0===a?void 0:a.parse())&&void 0!==ja?ja:null,this.state=null===this.oI?ha.EXTERNAL_XFDF_NOT_AVAILABLE:ha.EXTERNAL_XFDF_AVAILABLE,ba.label=2;case 2:if(this.state===ha.EXTERNAL_XFDF_NOT_AVAILABLE)return h(x),
[2];f=new DOMParser;n=f.parseFromString(x,"text/xml");y.forEach(function(ca){ea.merge(n,ea.oI,ca-1)});z=new XMLSerializer;w=z.serializeToString(n);h(w);return[2]}})})}};da.prototype.fM=function(aa){this.Kaa=aa};da.prototype.oe=function(){this.oI=void 0;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED};da.prototype.J6=function(aa){return aa?Array.isArray(aa)?new ka.a(aa):"string"!==typeof aa?null:(new DOMParser).parseFromString(aa,"text/xml").querySelector("xfdf > add")?new ka.a(aa):new ma.a(aa):null};da.prototype.merge=
function(aa,x,y){var h=this;0===y&&(this.Pea(aa,x.jp),this.Rea(aa,x.WH));var e=x.ca[y];e&&(this.Sea(aa,e.en),this.Uea(aa,e.ZZ,x.bw),this.Tea(aa,e.page,y),this.Qea(aa,e.SR));e=this.aa.Jb();if(y===e-1){var b=x.bw;Object.keys(b).forEach(function(a){b[a].DJ||h.FV(aa,a,b[a])})}};da.prototype.Pea=function(aa,x){null!==x&&(aa=this.pv(aa),this.Aq(aa,"calculation-order",x))};da.prototype.Rea=function(aa,x){null!==x&&(aa=this.pv(aa),this.Aq(aa,"document-actions",x))};da.prototype.Sea=function(aa,x){var y=this,
h=this.ov(aa.querySelector("xfdf"),"annots");Object.keys(x).forEach(function(e){y.Aq(h,'[name="'+e+'"]',x[e])})};da.prototype.Uea=function(aa,x,y){var h=this;if(0!==x.length){var e=this.pv(aa);x.forEach(function(b){var a=b.getAttribute("field"),f=y[a];f&&(h.FV(aa,a,f),h.Aq(e,"null",b))})}};da.prototype.FV=function(aa,x,y){var h=this.pv(aa);null!==y.WB&&this.Aq(h,'ffield [name="'+x+'"]',y.WB);aa=this.ov(aa.querySelector("xfdf"),"fields");x=x.split(".");this.pL(aa,x,0,y.value);y.DJ=!0};da.prototype.Tea=
function(aa,x,y){null!==x&&(aa=this.pv(aa),aa=this.ov(aa,"pages"),this.Aq(aa,'[number="'+(y+1)+'"]',x))};da.prototype.Qea=function(aa,x){Object.keys(x).forEach(function(y){(y=aa.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};da.prototype.pL=function(aa,x,y,h){if(y===x.length)x=document.createElementNS("","value"),x.textContent=h,this.Aq(aa,"value",x);else{var e=x[y];this.ov(aa,'[name="'+e+'"]',"field").setAttribute("name",e);aa=aa.querySelectorAll('[name="'+e+'"]');1===
aa.length?this.pL(aa[0],x,y+1,h):(e=this.x$(aa),this.pL(y===x.length-1?e:this.Gla(aa,e),x,y+1,h))}};da.prototype.x$=function(aa){for(var x=null,y=0;y<aa.length;y++){var h=aa[y];if(0===h.childElementCount||1===h.childElementCount&&"value"===h.children[0].tagName){x=h;break}}return x};da.prototype.Gla=function(aa,x){for(var y=0;y<aa.length;y++)if(aa[y]!==x)return aa[y];return null};da.prototype.Aq=function(aa,x,y){x=aa.querySelector(x);null!==x&&aa.removeChild(x);aa.appendChild(y)};da.prototype.pv=
function(aa){var x=aa.querySelector("pdf-info");if(null!==x)return x;x=this.ov(aa.querySelector("xfdf"),"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};da.prototype.ov=function(aa,x,y){var h=aa.querySelector(x);if(null!==h)return h;h=document.createElementNS("",y||x);aa.appendChild(h);return h};return da}();ua["default"]=Ba},456:function(Ba,ua){Ba=function(){function r(){}r.prototype.wA=function(pa){var ka=
{jp:null,WH:null,bw:{},ca:{}};pa=(new DOMParser).parseFromString(pa,"text/xml");ka.jp=pa.querySelector("pdf-info calculation-order");ka.WH=pa.querySelector("pdf-info document-actions");ka.bw=this.Mfa(pa);ka.ca=this.Yfa(pa);return ka};r.prototype.Mfa=function(pa){var ka=pa.querySelector("fields");pa=pa.querySelectorAll("pdf-info > ffield");if(null===ka&&null===pa)return{};var ma={};this.f4(ma,ka);this.d4(ma,pa);return ma};r.prototype.f4=function(pa,ka){if(null!==ka&&ka.children){for(var ma=[],ha=0;ha<
ka.children.length;ha++){var da=ka.children[ha];ma.push({name:da.getAttribute("name"),element:da})}for(;0!==ma.length;)for(ka=ma.shift(),ha=0;ha<ka.element.children.length;ha++)da=ka.element.children[ha],"value"===da.tagName?pa[ka.name]={value:da.textContent,WB:null,DJ:!1}:da.children&&ma.push({name:ka.name+"."+da.getAttribute("name"),element:da})}};r.prototype.d4=function(pa,ka){ka.forEach(function(ma){var ha=ma.getAttribute("name");pa[ha]?pa[ha].WB=ma:pa[ha]={value:null,WB:ma,DJ:!1}})};r.prototype.Yfa=
function(pa){var ka=this,ma={};pa.querySelectorAll("pdf-info widget").forEach(function(ha){var da=parseInt(ha.getAttribute("page"),10)-1;ka.WC(ma,da);ma[da].ZZ.push(ha)});pa.querySelectorAll("pdf-info page").forEach(function(ha){var da=parseInt(ha.getAttribute("number"),10)-1;ka.WC(ma,da);ma[da].page=ha});this.tT(pa).forEach(function(ha){var da=parseInt(ha.getAttribute("page"),10),aa=ha.getAttribute("name");ka.WC(ma,da);ma[da].en[aa]=ha});this.fT(pa).forEach(function(ha){var da=parseInt(ha.getAttribute("page"),
10);ha=ha.textContent;ka.WC(ma,da);ma[da].SR[ha]=!0});return ma};r.prototype.WC=function(pa,ka){pa[ka]||(pa[ka]={en:{},SR:{},ZZ:[],page:null})};return r}();ua.a=Ba},471:function(Ba,ua,r){var pa=r(1),ka=r(0);r.n(ka);Ba=function(ma){function ha(da){var aa=ma.call(this)||this;aa.j$=Array.isArray(da)?da:[da];return aa}Object(pa.c)(ha,ma);ha.prototype.parse=function(){var da=this,aa={jp:null,WH:null,bw:{},ca:{}};this.j$.forEach(function(x){aa=Object(ka.merge)(aa,da.wA(x))});return aa};ha.prototype.tT=
function(da){var aa=[];da.querySelectorAll("add > *").forEach(function(x){aa.push(x)});da.querySelectorAll("modify > *").forEach(function(x){aa.push(x)});return aa};ha.prototype.fT=function(da){return da.querySelectorAll("delete > *")};return ha}(r(456).a);ua.a=Ba},472:function(Ba,ua,r){var pa=r(1);Ba=function(ka){function ma(ha){var da=ka.call(this)||this;da.k$=ha;return da}Object(pa.c)(ma,ka);ma.prototype.parse=function(){return this.wA(this.k$)};ma.prototype.tT=function(ha){return ha.querySelectorAll("annots > *")};
ma.prototype.fT=function(){return[]};return ma}(r(456).a);ua.a=Ba}}]);}).call(this || window)
