/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{429:function(Ba,ua,r){r.r(ua);r.d(ua,"ByteRangeRequest",function(){return z});var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),ha=r(147);Ba=r(95);var da=r(245),aa=r(73),x=r(70),y=r(244),h=r(165);r=r(372);var e=[],b=[],a=window,f=function(){return function(){this.dm=1}}(),n;(function(ea){ea[ea.UNSENT=0]="UNSENT";ea[ea.DONE=4]="DONE"})(n||(n={}));var z=function(){function ea(ja,ba,ca,ia){var fa=this;this.url=ja;this.range=ba;this.df=ca;
this.withCredentials=ia;this.P1=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);a.Uint8Array&&(this.request.responseType="arraybuffer");ia&&(this.request.withCredentials=ia);w.DISABLE_RANGE_HEADER||(Object(ka.isUndefined)(ba.stop)?this.request.setRequestHeader("Range","bytes="+ba.start):this.request.setRequestHeader("Range",["bytes=",ba.start,"-",ba.stop-1].join("")));ca&&Object.keys(ca).forEach(function(la){fa.request.setRequestHeader(la,ca[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ea.prototype.start=function(ja){var ba=this,ca=this.request;ca.onreadystatechange=function(){if(ba.aborted)return ba.status=y.a.ABORTED,ja({code:y.a.ABORTED});if(this.readyState===ba.P1.DONE){ba.xC();var ia=0===window.document.URL.indexOf("file:///");200===ca.status||206===ca.status||ia&&0===ca.status?(ia=a.HT(this),ba.RM(ia,ja)):(ba.status=
y.a.ERROR,ja({code:ba.status,status:ba.status}))}};this.request.send(null);this.status=y.a.STARTED};ea.prototype.RM=function(ja,ba){this.status=y.a.SUCCESS;if(ba)return ba(!1,ja)};ea.prototype.abort=function(){this.xC();this.aborted=!0;this.request.abort()};ea.prototype.xC=function(){var ja=Object(h.c)(this.url,this.range,b);-1!==ja&&b.splice(ja,1);if(0<e.length){ja=e.shift();var ba=new ea(ja.url,ja.range,this.df,this.withCredentials);ja.request=ba;b.push(ja);ba.start(Object(h.d)(ja))}};ea.prototype.extend=
function(ja){var ba=Object.assign({},this,ja.prototype);ba.constructor=ja;return ba};return ea}(),w=function(ea){function ja(ba,ca,ia,fa,la){ia=ea.call(this,ba,ia,fa)||this;ia.gm={};ia.ZA=ca;ia.url=ba;ia.DISABLE_RANGE_HEADER=!1;ia.Ox=z;ia.MN=3;ia.df=la||{};return ia}Object(pa.c)(ja,ea);ja.prototype.Iv=function(ba,ca,ia){var fa=-1===ba.indexOf("?")?"?":"&";switch(ia){case !1:case x.a.NEVER_CACHE:ba=ba+fa+"_="+Object(ka.uniqueId)();break;case !0:case x.a.CACHE:ba=ba+fa+"_="+ca.start+","+(Object(ka.isUndefined)(ca.stop)?
"":ca.stop)}return ba};ja.prototype.ER=function(ba,ca,ia,fa){void 0===ia&&(ia={});return new this.Ox(ba,ca,ia,fa)};ja.prototype.Z9=function(ba,ca,ia,fa,la){for(var na=0;na<e.length;na++)if(Object(ka.isEqual)(e[na].range,ca)&&Object(ka.isEqual)(e[na].url,ba))return e[na].Kg.push(fa),e[na].AD++,null;for(na=0;na<b.length;na++)if(Object(ka.isEqual)(b[na].range,ca)&&Object(ka.isEqual)(b[na].url,ba))return b[na].Kg.push(fa),b[na].AD++,null;ia={url:ba,range:ca,ZA:ia,Kg:[fa],AD:1};if(0===e.length&&b.length<
this.MN)return b.push(ia),ia.request=this.ER(ba,ca,la,this.withCredentials),ia;e.push(ia);return null};ja.prototype.Xn=function(ba,ca,ia){var fa=this.Iv(ba,ca,this.ZA);(ba=this.Z9(fa,ca,this.ZA,ia,this.df))&&ba.request.start(Object(h.d)(ba));return function(){var la=Object(h.c)(fa,ca,b);if(-1!==la){var na=--b[la].AD;0===na&&b[la].request&&b[la].request.abort()}else la=Object(h.c)(fa,ca,e),-1!==la&&(na=--e[la].AD,0===na&&e.splice(la,1))}};ja.prototype.kT=function(){return{start:-ha.a}};ja.prototype.Fca=
function(){var ba=-(ha.a+ha.e);return{start:ba-ha.d,end:ba}};ja.prototype.jt=function(ba){var ca=this;this.eB=!0;var ia=ha.a;this.Xn(this.url,this.kT(),function(fa,la,na){function qa(){var ra=ca.Zd.gT();ca.Xn(ca.url,ra,function(ta,va){if(ta)return Object(ma.j)("Error loading central directory: "+ta),ba(ta);va=Object(aa.a)(va);if(va.length!==ra.stop-ra.start)return ba("Invalid XOD file: Zip central directory data is wrong size! Should be "+(ra.stop-ra.start)+" but is "+va.length);ca.Zd.cX(va);ca.yH=
!0;ca.eB=!1;return ba(!1)})}if(fa)return Object(ma.j)("Error loading end header: "+fa),ba(fa,la,na);la=Object(aa.a)(la);if(la.length!==ia)return ba("Invalid XOD file: Zip end header data is wrong size!");try{ca.Zd=new da.a(la)}catch(ra){return ba(ra)}ca.Zd.iea?ca.Xn(ca.url,ca.Fca(),function(ra,ta){if(ra)return Object(ma.j)("Error loading zip64 header: "+ra),ba(ra);ta=Object(aa.a)(ta);ca.Zd.Bea(ta);qa()}):qa()})};ja.prototype.DT=function(ba){ba(Object.keys(this.Zd.wn))};ja.prototype.sL=function(ba,
ca){var ia=this;if(this.Zd.tR(ba)){var fa=this.Zd.rC(ba);if(fa in this.gm){var la=this.Wh[ba];la.Sr=this.gm[fa];la.Sr.dm++;la.cancel=la.Sr.cancel}else{var na=this.Zd.Raa(ba),qa=this.Xn(this.url,na,function(ta,va){ta?(Object(ma.j)('Error loading part "'+ba+'": '+ta),ia.Xn(ia.url,na,function(oa,wa){if(oa)return ca(oa,ba);ia.gX(wa,na,fa,ba,ca)})):ia.gX(va,na,fa,ba,ca)}),ra=this.Wh[ba];ra&&(ra.iZ=!0,ra.cancel=function(){ra.Sr.dm--;0===ra.Sr.dm&&(qa(),delete ia.gm[fa])},this.gm[fa]=new f(fa),ra.Sr=this.gm[fa],
ra.Sr.cancel=ra.cancel)}}else delete this.Wh[ba],ca(Error('File not found: "'+ba+'"'),ba)};ja.prototype.gX=function(ba,ca,ia,fa,la){if(ba.length!==ca.stop-ca.start)la(Error("Part data is wrong size!"),fa);else{do{if(!this.gm[ia])return;fa=this.gm[ia].dm;for(var na=ca.Bq.length,qa=0;qa<na;++qa){var ra=ca.Bq[qa];la(!1,ra.xq,ba["string"===typeof ba?"substring":"subarray"](ra.start,ra.stop),this.Zd.IU(ra.xq));ra.xq in this.Wh&&delete this.Wh[ra.xq]}}while(fa!==this.gm[ia].dm);delete this.gm[ia]}};ja.DISABLE_RANGE_HEADER=
!1;ja.MN=3;return ja}(Ba.a);(function(ea){function ja(ba,ca,ia){var fa=ea.call(this)||this,la;for(la in ba)fa[la]=ba[la];fa.Fpa=ba;fa.startOffset=ca;fa.endOffset=ia;fa.ER=function(na,qa,ra,ta){Object(ka.isUndefined)(qa.stop)?(qa.start+=fa.endOffset,qa.stop=fa.endOffset):(qa.start+=fa.startOffset,qa.stop+=fa.startOffset);na=fa.Iv(fa.url,qa,fa.ZA);return new ba.Ox(na,qa,ra,ta)};return fa}Object(pa.c)(ja,ea);return ja})(w);Object(r.a)(w);Object(r.b)(w);ua["default"]=w}}]);}).call(this || window)
