/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{438:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),ha=r(147);Ba=r(49);var da=r(95),aa=r(245),x=r(70),y=r(244);r=r(372);var h=window,e=function(){function f(n,z,w){var ea=-1===n.indexOf("?")?"?":"&";switch(z){case x.a.NEVER_CACHE:this.url=n+ea+"_="+Object(ka.uniqueId)();break;default:this.url=n}this.df=w;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}f.prototype.start=function(n,z){var w=this,ea=this,ja=this.request,ba;ea.bx=0;n&&Object.keys(n).forEach(function(ca){w.request.setRequestHeader(ca,n[ca])});z&&(this.request.withCredentials=z);this.$D=setInterval(function(){var ca=0===window.document.URL.indexOf("file:///");ca=200===ja.status||
ca&&0===ja.status;if(ja.readyState!==y.b.DONE||ca){try{ja.responseText}catch(ia){return}ea.bx<ja.responseText.length&&(ba=ea.Sga())&&ea.trigger(f.Events.DATA,[ba]);0===ja.readyState&&(clearInterval(ea.$D),ea.trigger(f.Events.DONE))}else clearInterval(ea.$D),ea.trigger(f.Events.DONE,["Error received return status "+ja.status])},1E3);this.request.send(null);this.status=y.a.STARTED};f.prototype.Sga=function(){var n=this.request,z=n.responseText;if(0!==z.length)if(this.bx===z.length)clearInterval(this.$D),
this.trigger(f.Events.DONE);else return z=Math.min(this.bx+3E6,z.length),n=h.HT(n,this.bx,!0,z),this.bx=z,n};f.prototype.abort=function(){clearInterval(this.$D);var n=this;this.request.onreadystatechange=function(){Object(ma.j)("StreamingRequest aborted");n.status=y.a.ABORTED;return n.trigger(f.Events.ABORTED)};this.request.abort()};f.prototype.finish=function(){var n=this;this.request.onreadystatechange=function(){n.status=y.a.SUCCESS;return n.trigger(f.Events.DONE)};this.request.abort()};f.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return f}();Object(Ba.a)(e);var b;(function(f){f[f.LOCAL_HEADER=0]="LOCAL_HEADER";f[f.FILE=1]="FILE";f[f.CENTRAL_DIR=2]="CENTRAL_DIR"})(b||(b={}));var a=function(f){function n(){var z=f.call(this)||this;z.buffer="";z.state=b.LOCAL_HEADER;z.IM=4;z.Pl=null;z.ot=ha.c;z.wn={};return z}Object(pa.c)(n,f);n.prototype.Lga=function(z){var w;for(z=this.buffer+z;z.length>=this.ot;)switch(this.state){case b.LOCAL_HEADER:this.Pl=w=this.Wga(z.slice(0,this.ot));if(w.Wt!==
ha.g)throw Error("Wrong signature in local header: "+w.Wt);z=z.slice(this.ot);this.state=b.FILE;this.ot=w.oH+w.pq+w.aw+this.IM;this.trigger(n.Events.HEADER,[w]);break;case b.FILE:this.Pl.name=z.slice(0,this.Pl.pq);this.wn[this.Pl.name]=this.Pl;w=this.ot-this.IM;var ea=z.slice(this.Pl.pq+this.Pl.aw,w);this.trigger(n.Events.FILE,[this.Pl.name,ea,this.Pl.FH]);z=z.slice(w);if(z.slice(0,this.IM)===ha.h)this.state=b.LOCAL_HEADER,this.ot=ha.c;else return this.state=b.CENTRAL_DIR,!0}this.buffer=z;return!1};
n.Events={HEADER:"header",FILE:"file"};return n}(aa.a);Object(Ba.a)(a);Ba=function(f){function n(z,w,ea,ja,ba){ea=f.call(this,z,ea,ja)||this;ea.url=z;ea.stream=new e(z,w);ea.Zd=new a;ea.LW=window.createPromiseCapability();ea.mX={};ea.df=ba;return ea}Object(pa.c)(n,f);n.prototype.Ux=function(z){var w=this;this.request([this.oj,this.Fk,this.nj]);this.stream.addEventListener(e.Events.DATA,function(ea){try{if(w.Zd.Lga(ea))return w.stream.finish()}catch(ja){throw w.stream.abort(),w.Xv(ja),z(ja),ja;}});
this.stream.addEventListener(e.Events.DONE,function(ea){w.pga=!0;w.LW.resolve();ea&&(w.Xv(ea),z(ea))});this.Zd.addEventListener(a.Events.HEADER,Object(ka.bind)(this.lX,this));this.Zd.addEventListener(a.Events.FILE,Object(ka.bind)(this.lha,this));return this.stream.start(this.df,this.withCredentials)};n.prototype.DT=function(z){var w=this;this.LW.promise.then(function(){z(Object.keys(w.Zd.wn))})};n.prototype.fo=function(){return!0};n.prototype.request=function(z){var w=this;this.pga&&z.forEach(function(ea){w.mX[ea]||
w.Sla(ea)})};n.prototype.lX=function(){};n.prototype.abort=function(){this.stream&&this.stream.abort()};n.prototype.Sla=function(z){this.trigger(da.a.Events.PART_READY,[{Ya:z,error:"Requested part not found",Ai:!1,Uf:!1}])};n.prototype.lha=function(z,w,ea){this.mX[z]=!0;this.trigger(da.a.Events.PART_READY,[{Ya:z,data:w,Ai:!1,Uf:!1,error:null,ad:ea}])};return n}(da.a);Object(r.a)(Ba);Object(r.b)(Ba);ua["default"]=Ba}}]);}).call(this || window)
