/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[16],{440:function(Ba,ua,r){function pa(){return!1}function ka(z,w,ea){if(!(w in n))return!0;w=n[w];for(var ja=0;ja<w.length;ja++){var ba=z;var ca=w[ja];var ia=ea;if(ca.name in ba){var fa="",la=!1;ba=ba[ca.name];switch(ca.type){case "s":fa="String";la=Object(ha.isString)(ba);break;case "a":fa="Array";la=Object(ha.isArray)(ba);break;case "n":fa="Number";la=Object(ha.isNumber)(ba)&&Object(ha.isFinite)(ba);break;case "o":fa="Object",
la=Object(ha.isObject)(ba)&&!Object(ha.isArray)(ba)}la||ia.reject('Expected response field "'+ca.name+'" to have type '+fa);ca=la}else ia.reject('Response missing field "'+ca.name+'"'),ca=!1;if(!ca)return!1}return!0}r.r(ua);var ma=r(1),ha=r(0);r.n(ha);var da=r(2);Ba=r(49);var aa=r(32),x=r(458),y=r(95),h=r(372),e=r(40),b=r(165),a=function(){function z(){this.request=this.result=null;this.state=0;var w=this;w.promise=new Promise(function(ea,ja){w.resolve=function(){if(0===w.state||4===w.state)w.state=
1,w.result=arguments[0],ea.apply(null,arguments)};w.reject=function(){if(0===w.state||4===w.state)w.state=2,ja.apply(null,arguments)}})}z.prototype.bt=function(){return 1===(this.state&1)};z.prototype.Xda=function(){return 2===(this.state&2)};z.prototype.Mi=function(){return!this.Xda()&&!this.bt()};z.prototype.yda=function(){return 4===(this.state&4)};z.prototype.gM=function(){this.state|=4};return z}(),f=function(){function z(){this.Ls={};this.Eb=[]}z.prototype.pop=function(){var w=this.Eb.pop();
this.Ls[w.key]=void 0;return w};z.prototype.push=function(w,ea){ea={key:w,data:ea};this.Eb.push(ea);this.Ls[w]=ea.data};z.prototype.contains=function(w){return!!this.Ls[w]};z.prototype.get=function(w){return this.Ls[w]};z.prototype.set=function(w,ea){var ja=this;this.Ls[w]=ea;this.Eb.forEach(function(ba,ca){ba.key===w&&(ja.Eb[ca]=ba)})};z.prototype.remove=function(w){var ea=this;this.Ls[w]=void 0;this.Eb.forEach(function(ja,ba){ja.key===w&&ea.Eb.splice(ba,1)})};z.prototype.length=function(){return this.Eb.length};
return z}(),n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},
{name:"rID",type:"s"}]};r=function(){function z(w,ea,ja){var ba=this;this.JM=this.$R=!1;this.ah=this.jF=this.mu=this.IK=this.qH=this.vm=null;this.Xl=new a;this.qp=new a;this.pB=!1;this.vf=this.ze=this.Ae=this.mf=null;this.Jf=[];this.bC=[];this.cache={};this.timeStamp=0;this.Wg=[];this.Wi=[];this.sI=null;this.OR=!1;this.oY=this.id=null;this.wK=this.nU=pa;this.Yh=0;this.AJ=!1;this.SV=1;this.Ri={};this.Hr=0;this.Ft=new f;ea.endsWith("/")||(ea+="/");ja=ja||{};this.$R=ja.disableWebsockets||!1;this.JM=
ja.singleServerMode||!1;null!=ja.customQueryParameters&&Object(e.b)("wvsQueryParameters",ja.customQueryParameters);ea.endsWith("blackbox/")||(ea+="blackbox/");this.vm=ja.uploadData||null;this.mu=ja.uriData||null;this.qH=ja.cacheKey||null;this.IK=ja.officeOptions||null;this.Se=ea;this.VH=w;this.mo(!0);this.Wr=(new x.a(ea,null,this.Jh())).O$(!this.$R,function(ca){ba.pfa(ca)},function(){return null},function(){ba.pB=!1},function(){ba.sia()})}z.prototype.w7=function(){var w=this;return new Promise(function(ea,
ja){var ba=new XMLHttpRequest;ba.open("GET",w.Se+"ck");ba.withCredentials=w.Jh();ba.onreadystatechange=function(){ba.readyState===XMLHttpRequest.DONE&&(200===ba.status?ea():ja())};ba.send()})};z.prototype.Uja=function(w){this.nU=w||pa;this.wK=pa};z.prototype.d6=function(){this.TX();return this.Wr.Bp(!0)};z.prototype.TX=function(){Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return this.qp=new a,this.Xl=new a,this.pB=!1,this.id=null,this.OR=
!1,[4,this.w7()];case 1:return w.ea(),[2]}})})};z.prototype.sia=function(){this.nU();this.TX();this.mf&&(this.mf.Mi()?this.jh(this.mf.request):this.mf.bt()&&this.wK(this.mf.result.url,"pdf")&&(this.mf=null,this.SX()));this.vf&&this.vf.Mi()&&this.jh(this.vf.request);this.Ae&&this.Ae.Mi()?this.jh(this.Ae.request):this.ze&&this.ze.Mi()&&this.aU();var w;for(w=0;w<this.Wg.length;w++)this.Wg[w]&&(this.Wg[w].Mi()?this.jh(this.Wg[w].request):this.Wg[w].bt()&&this.wK(this.Wg[w].result.url,"image")&&(this.Wg[w]=
null,this.kE(Object(ha.uniqueId)(),w)));for(w=0;w<this.Wi.length;w++)this.Wi[w]&&this.Wi[w].Mi()&&!this.Wi[w].yda()&&this.jh(this.Wi[w].request);for(w=0;w<this.Jf.length;w++)this.Jf[w]&&this.Jf[w].Mi()&&this.jh(this.Jf[w].request)};z.prototype.ida=function(){return this.pB?Promise.resolve():(this.pB=!0,this.timeStamp=Date.now(),this.Wr.XC())};z.prototype.nma=function(){var w=this,ea,ja,ba,ca,ia;return new Promise(function(fa,la){if(w.vm)ea=new FormData,ea.append("file",w.vm.fileHandle,w.vm.fileHandle.name),
ja=w.vm.loadCallback,ca="upload",ba=w.vm.extension;else if(w.mu)ea={uri:w.mu.uri,Zpa:w.mu.shareId},ea=Object.keys(ea).map(function(ra){return ra+"="+(ea[ra]?encodeURIComponent(ea[ra]):"")}).join("&"),ia="application/x-www-form-urlencoded; charset=UTF-8",ja=w.mu.loadCallback,ca="url",ba=w.mu.extension;else{fa();return}var na=new XMLHttpRequest,qa=Object(aa.j)(w.Se,"AuxUpload");qa=Object(b.a)(qa,{type:ca,ext:ba});na.open("POST",qa);na.withCredentials=w.Jh();ia&&na.setRequestHeader("Content-Type",ia);
na.addEventListener("load",function(){if(na.readyState===na.DONE&&200===na.status){var ra=JSON.parse(na.response);w.VH=ra.uri;ja(ra);fa(ra)}});na.addEventListener("error",function(){la(na.statusText+" "+JSON.stringify(na))});w.vm&&null!=w.vm.onProgress&&(na.upload.onprogress=function(ra){w.vm.onProgress(ra)});na.send(ea)})};z.prototype.jia=function(w){this.password=w||null;this.Xl.bt()||(this.Xl=new a,this.jh({t:"pages"}));return this.Xl.promise};z.prototype.Ux=function(w){this.sI=w||null;this.Xl.bt()||
this.jh({t:"pages"});return this.Xl.promise};z.prototype.Hv=function(w){w=Object.assign(w,{uri:encodeURIComponent(this.VH)});this.sI&&(w.ext=this.sI);this.ah&&(w.c=this.ah);this.password&&(w.pswd=this.password);this.qH&&(w.cacheKey=this.qH);this.IK&&(w.officeOptions=this.IK);return w};z.prototype.Qia=function(){0<this.Ft.length()&&10>=this.Hr&&this.Ria(this.Ft.pop().data)};z.prototype.E5=function(w){0<this.Ft.length()&&this.Ft.contains(w)&&this.Ft.remove(w)};z.prototype.jh=function(w){w=this.Hv(w);
this.Wr.send(w)};z.prototype.kY=function(w,ea){10<this.Hr?this.Ft.push(w,ea):(this.Hr++,w=this.Hv(ea),this.Wr.send(w))};z.prototype.Ria=function(w){this.Hr++;w=this.Hv(w);this.Wr.send(w)};z.prototype.hl=function(w){return w};z.prototype.mU=function(w){this.JM&&w?Object(da.j)("Server failed health check. Single server mode ignoring check."):!this.Coa&&w&&3>=this.Yh?(this.AJ=!0,this.Wr.Bp()):3<this.Yh&&(this.JM=!0)};z.prototype.pfa=function(w){var ea=this,ja=w.data,ba=w.err,ca=w.t;switch(ca){case "upload":ba?
this.oma.reject(ba):this.oma.resolve("Success");break;case "pages":ba?this.Xl.reject(ba):ka(ja,ca,this.Xl)&&this.Xl.resolve(ja);break;case "config":if(ba)this.qp.reject(ba);else if(ka(ja,ca,this.qp)){this.mU(ja.unhealthy);ja.id&&(this.id=ja.id);if(ja.auth){var ia=Object(e.a)("wvsQueryParameters");ia.auth=ja.auth;Object(e.b)("wvsQueryParameters",ia)}ja.serverVersion&&(this.jF=ja.serverVersion,Object(da.h)("[WebViewer Server] server version: "+this.jF));ja.serverID?(this.Yh=ja.serverID===this.oY&&this.AJ?
this.Yh+1:0,this.oY=ja.serverID):this.Yh=0;this.AJ=!1;this.qp.resolve(ja)}break;case "health":ba?this.qp.reject(ba):ka(ja,ca,this.qp)&&this.mU(ja.unhealthy);break;case "pdf":ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url));ba?this.mf.reject(ba):ka(ja,ca,this.mf)&&this.mf.resolve(ja);break;case "ApString2Xod":ja.url=Object(b.a)(this.Se+"../data/"+encodeURI(ja.url));ba?this.Ri[ja.rID].reject(ba):ka(ja,ca,this.Ri[ja.rID])&&this.Ri[ja.rID].resolve(ja);break;case "docmod":ja.url=Object(b.a)(this.Se+
"../"+encodeURI(ja.url));ba?this.Ri[ja.rID].reject(ba):ka(ja,ca,this.mf)&&this.Ri[ja.rID].resolve(ja);break;case "xod":if(ba)this.Ae&&this.Ae.Mi()&&this.Ae.reject(ba),this.ze&&this.ze.Mi()&&this.ze.reject(ba);else if(ja.notFound)ja.noCreate||this.Ae&&this.Ae.Mi()&&this.Ae.resolve(ja),this.ze&&this.ze.Mi()&&this.ze.resolve(ja);else{ja.url&&(ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url)));if(!this.ze||this.ze.bt())this.ze=new a,this.ze.request={t:"xod",noCreate:!0};this.Ae||(this.Ae=new a,this.Ae.request=
{t:"xod"});this.ze.resolve(ja);this.Ae.resolve(ja)}break;case "cAnnots":ia=this.vf;if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){ia.gM();var fa=[],la=ja.annots;ja=function(oa){var wa=la[oa].s,Da=la[oa].e,Ia=na.Se+"../"+encodeURI(la[oa].xfdf),Ma="true"===la[oa].hasAppearance?Object(b.a)(Ia+".xodapp"):null,Ca=Object(ha.range)(wa,Da+1);fa[oa]={range:Ca,promise:new Promise(function(La,Sa){var Ka=new XMLHttpRequest;Ka.open("GET",Object(b.a)(Ia));Ka.responseType="text";Ka.withCredentials=ea.Jh();Ka.addEventListener("load",
function(){Ka.readyState===Ka.DONE&&200===Ka.status&&La({ar:Ka.response,Xk:Ma,range:Ca})});Ka.addEventListener("error",function(){Sa(Ka.statusText+" "+JSON.stringify(Ka))});Ka.send()})}};var na=this;for(ba=0;ba<la.length;ba++)ja(ba);ia.resolve(fa)}break;case "annots":if(ba)this.vf.reject(ba);else if(ka(ja,ca,this.vf)){this.vf.gM();var qa=new XMLHttpRequest;ia=this.Se+"../"+encodeURI(ja.url);var ra=ja.hasAppearance?Object(b.a)(ia+".xodapp"):null;qa.open("GET",Object(b.a)(ia));qa.responseType="text";
qa.withCredentials=this.Jh();qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ea.vf.resolve({ar:qa.response,Xk:ra})});qa.addEventListener("error",function(){ea.vf.reject(qa.statusText+" "+JSON.stringify(qa))});qa.send()}break;case "image":this.Hr--;var ta=this.Wg[ja.p];ba?ta.promise.reject(ba):ka(ja,ca,ta)&&(ta.result=ja,ta.result.url=Object(b.a)(this.Se+"../"+encodeURI(ta.result.url)),ta.resolve(ta.result));break;case "tiles":this.Hr--;ta=ja.rID;ia=this.Jf[ta];this.Jf[ta]=
null;this.bC.push(ta);if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){for(ba=0;ba<ja.tiles.length;ba++)ja.tiles[ba]=Object(b.a)(this.Se+"../"+encodeURI(ja.tiles[ba]));ia.resolve(ja)}break;case "text":ta=this.Wi[ja.p];if(ba)ta.reject(ba);else if(ka(ja,ca,ta)){ta.gM();var va=new XMLHttpRequest;ja=Object(b.a)(this.Se+"../"+encodeURI(ja.url));va.open("GET",ja);va.withCredentials=this.Jh();va.addEventListener("load",function(){va.readyState===va.DONE&&200===va.status&&(ta.result=JSON.parse(va.response),ta.resolve(ta.result))});
va.addEventListener("error",function(oa){ta.reject(va.statusText+" "+JSON.stringify(oa))});va.send()}break;case "progress":"loading"===ja.t&&this.trigger(y.a.Events.DOCUMENT_LOADING_PROGRESS,[ja.bytes,ja.total])}this.Qia();!ca&&w.echo&&w&&"apstring2xod"===w.echo.t&&(w=w.echo.reqID)&&(2<=parseInt(this.jF,10)?this.Ri[w].reject("Message unhandled by server"):this.Ri[w].reject())};z.prototype.taa=function(){return Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return[4,
this.ida()];case 1:return w.ea(),[2,this.qp.promise]}})})};z.prototype.caa=function(w){for(var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),ca=new FormData,ia={},fa=0;fa<w.body.length;fa++){var la=w.body[fa];ia[la.id]=la.dH.w+";"+la.dH.h;ca.append(la.id,la.dH.dataString)}w={t:"apstring2xod",reqID:this.SV++,parts:ia};var na=this.Hv(w);ca.append("msg",JSON.stringify(na));this.Ri[na.reqID]=new a;ja.open("POST",ba);ja.withCredentials=this.Jh;ba=new Promise(function(qa,ra){ja.onreadystatechange=
function(){4===ja.readyState&&(200===ja.status?qa():ra("An error occurred while sending down appearance strings to the server"))}});ja.send(ca);return ba.then(function(){return ea.Ri[na.reqID].promise})};z.prototype.f6=function(){var w=this.jF.split("-")[0].split("."),ea=["1","5","9"];if(3!==w.length)throw Error("Invalid WVS version length.");if(3!==ea.length)throw Error("Invalid version length.");for(var ja=0;ja<w.length;++ja){if(ea.length===ja||w[ja]>ea[ja])return-1;if(w[ja]!==ea[ja])return 1}return 0};
z.prototype.np=function(){return 0>=this.f6()};z.prototype.BI=function(){this.vf||(this.vf=new a,this.np()?this.vf.request={t:"cAnnots"}:this.vf.request={t:"annots"},this.jh(this.vf.request));return this.vf.promise};z.prototype.kE=function(w,ea){this.Wg[ea]||(this.Wg[ea]=new a,this.Wg[ea].request={t:"image",p:ea},this.kY(w,this.Wg[ea].request));return this.Wg[ea].promise};z.prototype.kia=function(w){this.Wi[w]||(this.Wi[w]=new a,this.Wi[w].request={t:"text",p:w},this.jh(this.Wi[w].request));return this.Wi[w].promise};
z.prototype.lia=function(w,ea,ja,ba,ca){var ia=this.Jf.length;this.bC.length&&(ia=this.bC.pop());this.Jf[ia]=new a;this.Jf[ia].request={t:"tiles",p:ea,z:ja,r:ba,size:ca,rID:ia};this.kY(w,this.Jf[ia].request);return this.Jf[ia].promise};z.prototype.SX=function(){this.mf||(this.mf=new a,this.mf.request={t:"pdf"},this.OR?this.mf.resolve({url:this.VH}):this.jh(this.mf.request));return this.mf.promise};z.prototype.vT=function(w){var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),
ca=new FormData,ia={};w.annots&&(ia.annots="xfdf");w.watermark&&(ia.watermark="png");w.redactions&&(ia.redactions="redact");ia={t:"docmod",reqID:this.SV++,parts:ia};w.print&&(ia.print=!0);var fa=this.Hv(ia);ca.append("msg",JSON.stringify(fa));return Promise.all([w.annots,w.watermark,w.redactions].map(function(la){return Promise.resolve(la)})).then(function(la){var na=la[0],qa=la[1];la=la[2];na&&ca.append("annots",na);qa&&ca.append("watermark",qa);la&&ca.append("redactions",la);ea.Ri[fa.reqID]=new a;
ja.open("POST",ba);ja.withCredentials=ea.Jh;na=new Promise(function(ra,ta){ja.onreadystatechange=function(){4===ja.readyState&&(200===ja.status?ra():ta("An error occurred while sending down annotation data to the server"))}});ja.send(ca);return na.then(function(){return ea.Ri[fa.reqID].promise})})};z.prototype.aU=function(){this.ze||(this.ze=new a,this.ze.request={t:"xod",noCreate:!0},this.jh(this.ze.request));return this.ze.promise};z.prototype.mia=function(){this.Ae||(this.Ae=new a,this.Ae.request=
{t:"xod"},this.jh(this.Ae.request));return this.Ae.promise};z.prototype.fo=function(){return!0};z.prototype.request=function(){};z.prototype.lX=function(){};z.prototype.abort=function(){for(var w=0;w<this.Jf.length;w++)this.Jf[w]&&(this.Jf[w].resolve(null),this.Jf[w]=null,this.bC.push(w));this.close()};z.prototype.wE=function(w){this.ah=this.ah||{};this.ah.headers=w};z.prototype.mo=function(w){this.ah=this.ah||{};this.ah.internal=this.ah.internal||{};this.ah.internal.withCredentials=w};z.prototype.Jh=
function(){return this.ah&&this.ah.internal?this.ah.internal.withCredentials:null};z.prototype.getFileData=function(){return Promise.reject()};return z}();Object(Ba.a)(r);Object(h.a)(r);Object(h.b)(r);ua["default"]=r},458:function(Ba,ua,r){var pa=r(1),ka=r(2),ma=r(32),ha=r(40),da=r(165),aa=r(113),x=function(){function h(e,b,a,f,n,z){void 0===a&&(a=null);void 0===f&&(f=null);void 0===n&&(n=null);void 0===z&&(z=null);this.zV=!1;this.Yh=0;this.TQ=this.Jma(e);this.url=b?this.TQ+"/"+b:this.TQ+"/ws";this.OH=
a;this.yx=f;this.Fv=n;this.NL=z}h.prototype.Jma=function(e){var b=e.indexOf("://"),a="ws://";0>b?b=0:(5===b&&(a="wss://"),b+=3);var f=e.lastIndexOf("/");0>f&&(f=e.length);return a+e.slice(b,f)};h.prototype.send=function(e){this.zo.readyState===WebSocket.CLOSED||this.zV||this.zo.send(JSON.stringify(e))};h.prototype.XC=function(){return Object(pa.b)(this,void 0,void 0,function(){var e,b=this;return Object(pa.d)(this,function(){e=Object(ha.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(ha.b)("wvsQueryParameters",
e);return[2,new Promise(function(a,f){var n=Object(da.a)(b.url);b.zo=new WebSocket(n);b.zo.onopen=function(){b.yx&&b.yx();a()};b.zo.onerror=function(z){b.zV=!0;f(z)};b.zo.onclose=function(z){var w=z.code;return Object(pa.b)(b,void 0,void 0,function(){var ea=this;return Object(pa.d)(this,function(ja){switch(ja.label){case 0:return this.Fv&&this.Fv(),3E3===w?[3,3]:8>this.Yh++?[4,new Promise(function(ba){return setTimeout(function(){return Object(pa.b)(ea,void 0,void 0,function(){return Object(pa.d)(this,
function(ca){switch(ca.label){case 0:return this.NL(),[4,this.XC()];case 1:return ca.ea(),ba(),[2]}})})},3E3)})]:[3,2];case 1:return ja.ea(),[3,3];case 2:f(aa.a),ja.label=3;case 3:return[2]}})})};b.zo.onmessage=function(z){z&&z.data&&(z=JSON.parse(z.data),z.hb?b.send({hb:!0}):z.end?close():b.OH(z))}})]})})};h.prototype.Bp=function(e){void 0===e&&(e=!1);this.Yh=0;e?this.zo.close(3E3):this.zo.close();return Promise.resolve()};return h}(),y=function(){function h(e,b,a,f,n,z,w){void 0===f&&(f=null);void 0===
n&&(n=null);void 0===z&&(z=null);void 0===w&&(w=null);this.Yh=this.jE=this.id=0;this.Lw=!1;this.request=null;e=this.Kga(e);this.url=b?e+"/"+b+"pf":e+"/pf";this.cF=a;this.OH=f;this.yx=n;this.Fv=z;this.NL=w}h.prototype.Kga=function(e){var b=e.lastIndexOf("/");0>b&&(b=e.length);return e.slice(0,b)};h.prototype.f7=function(e){e=e.split("\n");for(e[e.length-1]&&e.pop();0<e.length&&3>e[e.length-1].length;)"]"===e.pop()&&(this.id=0);0<e.length&&3>e[0].length&&e.shift();for(var b=0;b<e.length;++b)e[b].endsWith(",")&&
(e[b]=e[b].substr(0,e[b].length-1));return e};h.prototype.bY=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(b){switch(b.label){case 0:return 8>this.Yh++?[4,new Promise(function(a){return setTimeout(function(){e.NL();e.XC();a()},3E3)})]:[3,2];case 1:b.ea(),b.label=2;case 2:return[2]}})})};h.prototype.Mga=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a;return Object(pa.d)(this,function(f){switch(f.label){case 0:b=null,a=0,f.label=
1;case 1:if(!(a<e.length))return[3,6];b=JSON.parse(e[a]);if(!b)return[3,5];if(!b.end)return[3,2];close();return[3,5];case 2:if(!b.id||Number(b.id)===this.id)return[3,4];Object(ka.j)("Reconnecting, new server detected");this.Bp();return[4,this.bY()];case 3:return f.ea(),[3,5];case 4:b.hb&&Number(b.id)===this.id?this.send({hb:!0}):this.Lw||this.OH(b),f.label=5;case 5:return++a,[3,1];case 6:return[2]}})})};h.prototype.mfa=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a,f;return Object(pa.d)(this,
function(n){switch(n.label){case 0:if(!(3<=e.readyState))return[3,2];try{b=e.responseText.length}catch(z){return Object(ka.h)("caught exception"),[2]}if(0<b)try{a=this.f7(e.responseText),0===this.id&&0<a.length&&(f=JSON.parse(a.shift()),this.id=f.id,this.Yh=0),this.Mga(a)}catch(z){}return this.Lw?[3,2]:[4,this.CS()];case 1:n.ea(),n.label=2;case 2:return[2]}})})};h.prototype.CS=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(){return[2,new Promise(function(b,
a){function f(){return Object(pa.b)(e,void 0,void 0,function(){return Object(pa.d)(this,function(z){switch(z.label){case 0:a(),this.Bp(),z.label=1;case 1:return this.Lw&&8>this.Yh?[4,this.bY()]:[3,3];case 2:return z.ea(),[3,1];case 3:return[2]}})})}e.request=new XMLHttpRequest;e.request.withCredentials=e.cF;var n=Object(da.a)(e.url,0!==e.id?{id:String(e.id),uc:String(e.jE)}:{uc:String(e.jE)});e.jE++;e.request.open("GET",n,!0);e.request.setRequestHeader("Cache-Control","no-cache");e.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");e.request.onreadystatechange=function(){e.mfa(e.request)};e.request.addEventListener("error",f);e.request.addEventListener("timeout",f);e.request.addEventListener("load",function(){e.yx&&e.yx();b()});e.request.send()})]})})};h.prototype.XC=function(){var e=Object(ha.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(ha.b)("wvsQueryParameters",e);this.jE=this.id=0;this.Lw=!1;return this.CS()};h.prototype.send=function(e){var b=this,a=new XMLHttpRequest;a.withCredentials=this.cF;
var f=Object(da.a)(this.url,{id:String(this.id)}),n=new FormData;n.append("data",JSON.stringify(e));a.addEventListener("error",function(){b.Bp()});a.open("POST",f);a.setRequestHeader("X-Requested-With","XMLHttpRequest");a.send(n)};h.prototype.Bp=function(){this.id=0;this.Lw=!0;this.Fv&&this.Fv();this.request.abort();return Promise.resolve()};return h}();Ba=function(){function h(e,b,a){this.qR=e;this.target=b;this.cF=a}h.prototype.O$=function(e,b,a,f,n){void 0===e&&(e=!0);void 0===b&&(b=null);void 0===
a&&(a=null);void 0===f&&(f=null);void 0===n&&(n=null);return e?new x(this.qR,this.target,b,a,f,n):new y(this.qR,this.target,this.cF,b,a,f,n)};return h}();ua.a=Ba}}]);}).call(this || window)
